# Generated by Django 3.0.8 on 2020-08-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batch',
            field=models.CharField(max_length=15, verbose_name='Year of Passing'),
        ),
    ]
