# Generated by Django 3.0.8 on 2020-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200806_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='year_of_passing',
            field=models.CharField(default='', max_length=12),
        ),
    ]
