# Generated by Django 3.0.8 on 2020-08-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20200806_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='passing_year',
            field=models.CharField(max_length=12),
        ),
    ]
